### ISSUE TITLE
Generic endpoint to send any formatted message to some channel

### ISSUE THREAD

**Issue by alarsyo** [prologin/prololo#28]
The config would look something like:

```yaml
matrix_rooms:
  prololo-test:
    id: "changeme"
    default: true
  yakafet:
    id: "some_id"

generic_endpoints:
  - room: yakafet # must be a matrix_room above
    # final endpoint will be /api/webhook/generic/yakafet
    name: "yakafet"
    secret: "changeme please"
    # optional custom tag, otherwise name is used
    tag: "🍴 yakafet"
```
